uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg am_map.c
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg doomdef.c
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg doomstat.c
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg dstrings.c
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg d_items.c
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg d_main.c
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg d_net.c
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg f_finale.c
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg f_wipe.c
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg g_game.c
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg hu_lib.c
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg hu_stuff.c
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg info.c
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg i_main.c
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg i_net.c
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg i_sound.c
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg i_system.c
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg i_video.c
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg m_argv.c
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg m_bbox.c
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg m_cheat.c
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg m_fixed.c
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg m_menu.c
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg m_misc.c
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg m_random.c
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg m_swap.c
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg p_ceilng.c
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg p_doors.c
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg p_enemy.c
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg p_floor.c
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg p_inter.c
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg p_lights.c
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg p_map.c
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg p_maputl.c
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg p_mobj.c
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg p_plats.c
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg p_pspr.c
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg p_saveg.c
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg p_setup.c
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg p_sight.c
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg p_spec.c
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg p_switch.c
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg p_telept.c
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg p_tick.c
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg p_user.c
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg r_bsp.c
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg r_data.c
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg r_draw.c
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg r_main.c
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg r_plane.c
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg r_segs.c
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg r_sky.c
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg r_things.c
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg sounds.c
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg st_lib.c
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg st_stuff.c
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg s_sound.c
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg tables.c
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg v_video.c
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg wi_stuff.c
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg w_wad.c
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg z_zone.c
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg am_map.h
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg doomdata.h
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg doomdef.h
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg doomstat.h
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg doomtype.h
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg dstrings.h
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg d_englsh.h
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg d_event.h
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg d_french.h
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg d_items.h
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg d_main.h
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg d_net.h
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg d_player.h
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg d_textur.h
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg d_think.h
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg d_ticcmd.h
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg f_finale.h
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg f_wipe.h
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg g_game.h
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg hu_lib.h
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg hu_stuff.h
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg info.h
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg i_net.h
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg i_sound.h
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg i_system.h
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg i_video.h
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg m_argv.h
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg m_bbox.h
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg m_cheat.h
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg m_fixed.h
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg m_menu.h
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg m_misc.h
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg m_random.h
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg m_swap.h
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg p_inter.h
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg p_local.h
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg p_mobj.h
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg p_pspr.h
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg p_saveg.h
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg p_setup.h
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg p_spec.h
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg p_tick.h
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg r_bsp.h
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg r_data.h
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg r_defs.h
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg r_draw.h
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg r_local.h
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg r_main.h
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg r_plane.h
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg r_segs.h
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg r_sky.h
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg r_state.h
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg r_things.h
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg sounds.h
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg st_lib.h
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg st_stuff.h
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg s_sound.h
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg tables.h
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg v_video.h
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg wi_stuff.h
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg w_wad.h
uncrustify\uncrustify.exe --replace -c uncrustify\defaults.cfg z_zone.h
