OBJS = am_map.obj doomstat.obj dstrings.obj d_items.obj d_main.obj \
	d_net.obj f_finale.obj f_wipe.obj g_game.obj hu_lib.obj hu_stuff.obj \
	info.obj \
	m_argv.obj m_bbox.obj m_cheat.obj m_menu.obj m_misc.obj \
	m_random.obj p_ceilng.obj p_doors.obj p_enemy.obj p_floor.obj \
	p_inter.obj p_lights.obj p_map.obj p_maputl.obj p_mobj.obj p_plats.obj \
	p_pspr.obj p_saveg.obj p_setup.obj p_sight.obj p_spec.obj p_switch.obj \
	p_telept.obj p_tick.obj p_user.obj r_bsp.obj r_data.obj r_draw.obj \
	r_main.obj r_plane.obj r_segs.obj r_sky.obj r_things.obj sounds.obj \
	strcasecmp.obj strncasecmp.obj st_lib.obj st_stuff.obj s_sound.obj tables.obj \
	v_video.obj wi_stuff.obj w_wad.obj xmalloc.obj z_zone.obj \
	m_fixed.obj


CC = wcl386
MEM = /3s
ZOPT =
OPT = /Ox
CPU =
OS =
DEBUG = # /Zi
DEFINE =  -D_WATCOMC7_ -D__MSDOS__
INCLUDES =  -Iinclude

CFLAGS =  $(MEM) $(CPU) $(OPT)  $(OS) $(DEBUG) $(DEFINE) $(INCLUDES)
ZCFLAGS = $(MEM) $(CPU) $(ZOPT) $(OS) $(DEBUG) $(DEFINE) $(INCLUDES)


doom.exp: $(OBJS)
	386linkr @7
	copy /Y d.exe test

m_fixed.obj:
	\xenixnt\bin\ax386.exe ff.s -o m_fixed.obj

i_system.obj:
	$(CC) $(CFLAGS) /c phar4\i_system.c

xmalloc.obj:
	$(CC) $(CFLAGS) /c go32\xmalloc.c

xstrcasecmp.obj:
	$(CC) $(CFLAGS) /c /Fostrcase.obj strcasecmp.c
	@del /F strcasecmp.obj
	@ren strcase.obj strcasecmp.obj

xstrncasecmp.obj:
	$(CC) $(CFLAGS) /c /Fostrncase.obj strncasecmp.c
	@del /F strncasecmp.obj
	@ren strncase.obj strncasecmp.obj

i_video.obj:
#	$(CC) $(CFLAGS) /c phar4\i_video.c
	@echo build with watcom 10
	@echo wcc386 phar4\i_video.c  /3s -D__MSDOS__ -Iinclude

p_enemy.obj:
	@echo build with watcom 10
	@echo wcc386 p_enemy.c  /3s -D__MSDOS__ -Iinclude

p_inter.obj:
	@echo build with watcom 10
	@echo wcc386 p_inter.c  /3s /Od -D__MSDOS__ -Iinclude

p_map.obj:
	@echo build with watcom 10
	@echo wcc386 p_map.c  /3s /Od -D__MSDOS__ -Iinclude


